apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-k8s-deployment
  labels:
    app: django-k8s-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: django-k8s-deployment
  template:
    metadata:
      labels:
        app: django-k8s-deployment
    spec:
      containers:
      - name: django-k8s-web
        image: lewiskinyuanjue/django-k8s:v7
        envFrom:
        - secretRef:
            name: django  # Loads all variables from the secret
        env:
        - name: ALLOWED_HOSTS
          value: "django-k8s-web-service.default.svc.cluster.local"
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: django-k8s-web-service
spec:
  type: LoadBalancer  
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8000
  selector:
    app: django-k8s-deployment

